version: '3.8'
services:
  mqtt:
    container_name: eclipse-mosquitto
    image: eclipse-mosquitto:2.0.12
    volumes:
      - ./mosquitto_conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001